version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.14"
  jobs:
    post_checkout:
      - git lfs fetch
      - git lfs checkout

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements-docs.txt
