language: python

sudo: false

install:
  - pip install numpy
  - pip install numba
  - pip install pandas
  - pip install matplotlib
  - pip install scipy
  - pip install sympy
  - pip install openpyxl

script:
    - hydrostats/tests/tests.py