language: python

sudo: false

install:
  - pip install numpy >= 1.14.2
  - pip install numba >= 0.37.0
  - pip install pandas >= 0.22.0
  - pip install matplotlib >= 2.2.0
  - pip install scipy >= 1.0.0
  - pip install sympy >= 1.1.1
  - pip install openpyxl >= 2.5.2

script:
    - hydrostats/tests/tests.py