language: python

sudo: false

python:
  - 2.7
  - 3.5
  - 3.6

install:
  - pip install numpy
  - pip install numba==0.39
  - pip install pandas
  - pip install matplotlib
  - pip install scipy
  - pip install openpyxl
  - pip install HydroErr
  - pip install codecov

script:
  - cd hydrostats/tests
  - pwd
  - ls
  - python tests.py
  - coverage run tests.py

after_success:
  - codecov
