language: python

sudo: false

python:
  - 2.7
  - 3.5
  - 3.6

install:
  - pip install numpy
  - pip install numba
  - pip install pandas
  - pip install matplotlib
  - pip install scipy
  - pip install openpyxl
  - pip install HydroErr
  - pip install codecov
  - pip install coverage

script:
  - cd hydrostats/tests
  - coverage run tests.py

after_success:
  - codecov
